monolog:
    handlers:
        main:
            type: console
            level: notice

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        deprecation:
            type: console

        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]

        my_elastic:
            type: elasticsearch
            elasticsearch:
                host: '%env(ELASTIC_IP)%'
            index: prod-php
            document_type: php-logs
            level: notice
            ignore_error: true